set(_CATKIN_CURRENT_PACKAGE "finalProject")
set(finalProject_VERSION "0.0.0")
set(finalProject_MAINTAINER "jairo <jairo@todo.todo>")
set(finalProject_PACKAGE_FORMAT "2")
set(finalProject_BUILD_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(finalProject_BUILD_EXPORT_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(finalProject_BUILDTOOL_DEPENDS "catkin")
set(finalProject_BUILDTOOL_EXPORT_DEPENDS )
set(finalProject_EXEC_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(finalProject_RUN_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(finalProject_TEST_DEPENDS )
set(finalProject_DOC_DEPENDS )
set(finalProject_URL_WEBSITE "")
set(finalProject_URL_BUGTRACKER "")
set(finalProject_URL_REPOSITORY "")
set(finalProject_DEPRECATED "")