#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_fake:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_driving:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_msgs:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_detect:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_core:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_camera:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_2020:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/opencv_tests:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/apriltag_ros:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/image_geometry:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/finalProject:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/darknet_ros:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/darknet_ros_msgs:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment4_trackingandfollowing:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/cv_bridge:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/aue_finals:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment3a_wallfollowingandobstacleavoidance:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment2B_turtlebotteleop:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment1c_turtlebot3:/home/jairo/Desktop/AuE8230Spring23_JairoLeal/catkin_ws/devel:/home/jairo/catkin_ws/devel:/home/jairo/Desktop/Autonomy/ROS_workspace/devel:/opt/ros/noetic:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/apriltag'
export LD_LIBRARY_PATH='/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_driving/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_msgs/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_detect/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_core/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_camera/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/opencv_tests/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/apriltag_ros/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/image_geometry/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/finalProject/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/darknet_ros/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/darknet_ros_msgs/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment4_trackingandfollowing/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/cv_bridge/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/aue_finals/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment3a_wallfollowingandobstacleavoidance/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment2B_turtlebotteleop/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment1c_turtlebot3/lib:/home/jairo/Desktop/AuE8230Spring23_JairoLeal/catkin_ws/devel/lib:/home/jairo/catkin_ws/devel/lib:/home/jairo/Desktop/Autonomy/ROS_workspace/devel/lib:/opt/ros/noetic/lib:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/apriltag/lib'
export PATH='/opt/ros/noetic/bin:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/apriltag/bin:/home/jairo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_driving/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_msgs/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_detect/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_core/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_autorace_camera/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/opencv_tests/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/apriltag_ros/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/image_geometry/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/finalProject/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/darknet_ros/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/darknet_ros_msgs/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment4_trackingandfollowing/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/cv_bridge/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/aue_finals/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment3a_wallfollowingandobstacleavoidance/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment2B_turtlebotteleop/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/assignment1c_turtlebot3/lib/pkgconfig:/home/jairo/Desktop/AuE8230Spring23_JairoLeal/catkin_ws/devel/lib/pkgconfig:/home/jairo/catkin_ws/devel/lib/pkgconfig:/home/jairo/Desktop/Autonomy/ROS_workspace/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/apriltag/lib/pkgconfig'
export ROSLISP_PACKAGE_DIRECTORIES="/home/jairo/Desktop/AuE8230_Group3/catkin_ws/devel_isolated/turtlebot3_fake/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/jairo/Desktop/AuE8230_Group3/catkin_ws/src/turtlebot3_simulations/turtlebot3_fake:$ROS_PACKAGE_PATH"